export interface EnvironmentVariable {
    STACK_NAME: string;
    INCIDENT_DEGENERATION_DURATION: string;
    INCIDENT_RECOVERY_DURATION: string;
    INCIDENT_THRESHOLD_PERCENTAGE: string;
    INCIDENT_FLAG_BUCKET_NAME: string;
    INCIDENT_INTEGRATION_URL: string;
    INCIDENT_INTEGRATION_WEBHOOK: string;
}