language: node_js
node_js: "node"

dist: precise

env:
  - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
  - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  - AWS_DEFAULT_REGION=ap-southeast-1

install:
  - npm install
  
script:
  - npm run build
  - npm test
